version: '3'

services:
  app-local:
    container_name: app-local
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
    - 8080:8080
    volumes:
      - .:/app
