version: '3'

services:
  app:
    container_name: a_2016_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
    - 8080:8080
    volumes:
      - .:/app
  postgres:
    container_name: a_2016_postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=pizza
      - POSTGRES_PASSWORD=pizzatabetai
    volumes:
      - a_2016_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  a_2016_postgres_data:
