"""empty message

Revision ID: 2bf54958732a
Revises: a9f3064a80d8
Create Date: 2020-11-16 07:07:07.057620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf54958732a'
down_revision = 'a9f3064a80d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=1024), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('containers')
    # ### end Alembic commands ###
