"""empty message

Revision ID: 61f84152659b
Revises: 26c8cc1f1499
Create Date: 2020-11-24 09:16:26.820562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f84152659b'
down_revision = '26c8cc1f1499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('user_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'user_id')
    # ### end Alembic commands ###
