"""empty message

Revision ID: a9f3064a80d8
Revises: 878a472efca5
Create Date: 2020-11-05 11:30:11.041455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f3064a80d8'
down_revision = '878a472efca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('devices', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'expiration_date')
    op.drop_column('devices', 'color')
    # ### end Alembic commands ###
