"""empty message

Revision ID: d13ca010034c
Revises: 61f84152659b
Create Date: 2020-11-27 11:00:40.228531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13ca010034c'
down_revision = '61f84152659b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'url')
    # ### end Alembic commands ###
