"""empty message

Revision ID: d66be1bf5c41
Revises: 
Create Date: 2020-11-03 11:55:30.568114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66be1bf5c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
